name: Build for Android

on:
  [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm32", "aarch64", "x86_64" ]
      fail-fast: false

    name: "Build ${{matrix.arch}}"

    runs-on: ubuntu-20.04
    env:
      ANDROID_NDK_HOME: "${ANDROID_SDK_ROOT}/ndk-bundle"

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          mkdir -p /tmp/build/lib/pkgconfig
          cp libdrm.pc /tmp/build/lib/pkgconfig/
          if [ "${{matrix.arch}}" == "arm32" ]; then
            export ANDROID_TARGET=armv7a-linux-androideabi
          elif [ "${{matrix.arch}}" == "aarch64" ]; then
            export ANDROID_TARGET=aarch64-linux-android
          elif [ "${{matrix.arch}}" == "x86_64" ]; then
            export ANDROID_TARGET=x86_64-linux-android
          fi
          sudo pip3 install meson ninja
          sudo apt update
          sudo apt install libepoxy-dev libepoxy0 libvirglrenderer1 libvirglrenderer1-dev
          bash android-cross-file-gen.sh


      - name: Build libepoxy
        run: |
          git clone --depth 1 https://github.com/anholt/libepoxy.git
          cd libepoxy
          meson "build-android-${{matrix.arch}}" \
            --prefix=/tmp/build \
            --cross-file "/tmp/generated-cross-file" \
            -Ddefault_library=static \
            -Degl=yes -Dglx=no -Dx11=false
          ninja -C "build-android-${{matrix.arch}}" install

      - name: Build virglrenderer
        run: |
          meson "build-android-${{matrix.arch}}" \
            --prefix=/tmp/build \
            --cross-file "/tmp/generated-cross-file" \
            -Dplatforms=egl
          ninja -C "build-android-${{matrix.arch}}" install
          cp "build-android-${{matrix.arch}}/vtest/libvirgl_test_server.so" /tmp/build/lib/
      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: build_${{matrix.arch}}
          path: /tmp/build
